import { jsPDF } from 'jspdf';

export const generatePrivacyReport = (reportData) => {
  const doc = new jsPDF();
  const { fileName, fileSize, algorithms, score, summary, timestamp } = reportData;

  // Colors & Styles
  doc.setFillColor(5, 10, 21); // Deep Navy
  doc.rect(0, 0, 210, 297, 'F');

  doc.setTextColor(0, 240, 255); // Electric Blue
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('QuantumShield', 20, 30);
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text('Unified Privacy Report', 20, 45);

  // Separator
  doc.setDrawColor(0, 255, 136); // Neon Green
  doc.setLineWidth(0.5);
  doc.line(20, 52, 190, 52);

  // Metadata
  doc.setFontSize(12);
  doc.setTextColor(148, 163, 184); // Secondary Text
  doc.setFont('helvetica', 'normal');
  doc.text(`Timestamp: ${timestamp}`, 20, 65);
  doc.text(`Target File: ${fileName}`, 20, 75);
  doc.text(`Data Size: ${fileSize}`, 20, 85);

  // Algorithms
  doc.setTextColor(0, 240, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Protections Applied', 20, 105);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(255, 255, 255);
  algorithms.forEach((algo, idx) => {
    doc.text(`\u2022 ${algo}`, 25, 115 + (idx * 10));
  });

  // Score
  doc.setTextColor(0, 255, 136);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Overall Privacy Score', 20, 155);
  
  doc.setFontSize(36);
  doc.text(`${score}/100`, 20, 175);

  // Gemini Summary
  doc.setTextColor(0, 240, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('AI Protection Summary (Gemini Powered)', 20, 200);

  doc.setTextColor(148, 163, 184);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  const splitSummary = doc.splitTextToSize(summary, 170);
  doc.text(splitSummary, 20, 215);

  // Footer
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('Generated by QuantumShield - Next-Gen Privacy Infrastructure', 20, 280);

  doc.save(`QuantumShield_Report_${Date.now()}.pdf`);
};
